version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
     - ./fitocracy.db:/fitocracy-db/fitocracy.db
    environment:
      APP_HOME: /fitocracy-api
      DB_PATH: /fitocracy-db/fitocracy.db
      SESSION_SECRET: change_me
      GCLOUD_KEYRING_NAME: FitocracyApi          # Will be created if it doesn't exist
      GCLOUD_KEY_NAME: FitocracyCreds            # Will be created if it doesn't exist
      GCLOUD_PROJECT_ID: fitocracypal            # Needs to be created in advance
      GCLOUD_KEY_LOCATION: global
      GCLOUD_STORAGE_BUCKET: fit.fitocracypal.cf # Needs to be created in advance